name: VaultApp
options:
  bundleIdPrefix: com.intrex786
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""          # ← paste your Apple Team ID here
    CODE_SIGN_STYLE: Automatic

targets:
  VaultApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: App
        optional: true
      - path: Security
      - path: UI
      - path: Screens

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.intrex786.vaultapp
        PRODUCT_NAME: VaultApp
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/VaultApp.entitlements
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES

    info:
      path: App/Info.plist
      properties:
        CFBundleName: VaultApp
        CFBundleDisplayName: VaultApp
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundlePackageType: APPL
        CFBundleInfoDictionaryVersion: "6.0"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        # Privacy — required for Face ID
        NSFaceIDUsageDescription: "VaultApp uses Face ID to unlock your vault securely."
        # Privacy — required for iCloud
        NSUbiquitousContainers:
          iCloud.com.intrex786.vaultapp:
            NSUbiquitousContainerIsDocumentScopePublic: false
            NSUbiquitousContainerName: VaultApp
            NSUbiquitousContainerSupportedFolderLevels: None

    entitlements:
      path: App/VaultApp.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.intrex786.vaultapp
        keychain-access-groups:
          - "$(AppIdentifierPrefix)com.intrex786.vaultapp"
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.intrex786.vaultapp
        com.apple.developer.icloud-services:
          - CloudDocuments

    dependencies: []

    prebuildScripts:
      - name: SwiftLint (optional)
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          fi
        basedOnDependencyAnalysis: false
        showEnvVars: false
