name: VaultApp
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: "17.0"
targets:
  VaultApp:
    type: application
    platform: iOS
    sources:
      - Security
      - UI
      - Screens
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourname.vaultapp
        SWIFT_VERSION: 5.9
        TARGETED_DEVICE_FAMILY: 1
        INFOPLIST_FILE: Info.plist
